M48
; DRILL file {KiCad 7.0.2} date Thu Jul 13 20:15:54 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-13T20:15:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.0492Y0.9803
X1.0492Y0.8622
T2
X0.5689Y1.8602
X0.8839Y1.8602
T0
M30
