M48
; DRILL file {KiCad 7.0.2} date Thu Jul  6 19:43:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-06T19:43:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X5.3071Y-4.3346
X5.3071Y-4.4528
T2
X4.1797Y-4.628
X4.1797Y-4.9429
T0
M30
